language: java
jdk: oraclejdk8
dist: trusty
script: mvn clean package
deploy:
  provider: releases
  api_key:
    secure: 60784c76619f046f721cbd70d40d4b540a787913
  file:
    - /home/travis/build/MaoZa/PackDownLoad/target/Curse整合包下载器.exe
    - /home/travis/build/MaoZa/PackDownLoad/target/PackDownLoad.jar
  skip_cleanup: true
  on:
    tags: true
